# TASK:  the user has to guess a random number
# generated by Python between 1 and 20
# print hints with different colors

# import modules for the application
import random
from colorama import Fore, Back, Style

# generate a number
random_number = random.randint(1, 20)

# variable for making if-statement
user_guess = ""

# if-statement
if user_guess == random_number:
    False

# loop for checking user's inputs
while True:
    user_guess = int(input("Guess the number (1-20):\n"))
    if user_guess < random_number:
        print(Back.BLUE + "Too low.")
        print(Style.RESET_ALL)
    elif user_guess > random_number:
        print(Back.RED + "Too high.")
        print(Style.RESET_ALL)
    elif user_guess == random_number:
        print(Back.GREEN + "Congratulations!")
        print(Style.RESET_ALL)
        break